apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-server
  namespace: prometheus
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::350145996213:role/my-eks-cluster-prometheus-role
